# Generated by Django 4.2.2 on 2023-06-22 10:41

import django.core.validators
from django.db import migrations, models
import django_exam_prep_my_plants.webapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(max_length=14)),
                ('plant_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), django_exam_prep_my_plants.webapp.validators.validate_letters_only])),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinValueValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[django_exam_prep_my_plants.webapp.validators.validate_first_letter_is_upper])),
                ('last_name', models.CharField(max_length=20, validators=[django_exam_prep_my_plants.webapp.validators.validate_first_letter_is_upper])),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
